#!/usr/bin/env bash
# common/mavlink/message_definitions/argus.xml 에서 MAVLink C 헤더를 생성한다.
# 결과(common/mavlink/generated/)는 저장소에 커밋한다.
#
# 최초 실행 (로컬 가상환경, pymavlink 버전은 tools/requirements-mavgen.txt):
#   python3 -m venv ~/.venvs/mavgen && ~/.venvs/mavgen/bin/pip install -r tools/requirements-mavgen.txt
# 재생성 (argus.xml 수정 후):
#   MAVGEN_PYTHON=~/.venvs/mavgen/bin/python tools/generate_mavlink.sh
#
# - generated/ 를 지우고 다시 만든다 (argus.xml 에서 지운 메시지의 옛 헤더가 남지 않게)
# - mavgen 이 version.h 에 넣는 생성 날짜를 고정한다 (날짜가 매번 달라지면 CI 의 재생성·비교가 항상 실패한다)
# - mavgen 은 생성 파일에 표시를 넣지 않으므로 모든 .h 첫 줄에 "Code generated ... DO NOT EDIT." 를 붙인다
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
python="${MAVGEN_PYTHON:-python3}"
definitions="$repo_root/common/mavlink/message_definitions"
output="$repo_root/common/mavlink/generated"
banner="// Code generated by tools/generate_mavlink.sh from common/mavlink/message_definitions/argus.xml; DO NOT EDIT."

if ! "$python" -c "import pymavlink" 2>/dev/null; then
    echo "pymavlink 를 찾을 수 없습니다. MAVGEN_PYTHON 에 pymavlink 가 설치된 python 을 지정하세요." >&2
    exit 1
fi

rm -rf "$output"
"$python" -m pymavlink.tools.mavgen \
    --lang=C \
    --wire-protocol=2.0 \
    --output="$output" \
    "$definitions/argus.xml"

# 생성 날짜 고정
find "$output" -name 'version.h' -print0 |
    xargs -0 sed -i.bak 's/^#define MAVLINK_BUILD_DATE ".*"$/#define MAVLINK_BUILD_DATE "fixed; see git log of message_definitions"/'
find "$output" -name '*.bak' -delete

# 생성된 모든 헤더 첫 줄에 표시
find "$output" -name '*.h' -print0 | while IFS= read -r -d '' header; do
    printf '%s\n' "$banner" | cat - "$header" > "$header.tmp" && mv "$header.tmp" "$header"
done

# 생성 코드는 clang-format 대상에서 제외
printf 'DisableFormat: true\nSortIncludes: Never\n' > "$output/.clang-format"

pymavlink_version="$("$python" -c "import importlib.metadata as m; print(m.version('pymavlink'))")"
echo "생성 완료: $output ($(find "$output" -name '*.h' | wc -l | tr -d ' ')개 헤더, pymavlink $pymavlink_version)"
